# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pd2zAcTrLiUaJlVrw1aZBtO-s5T87_CT
"""

import numpy as np
import pandas as pd

import io
import pandas as pd
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
    df = pd.read_csv(io.BytesIO(uploaded[fn]))

print(df)

df.head()

df.info()

df.describe()

df.columns

#Check the timestamp column.
df['timestamp'].head(10)

df['timestamp'].value_counts().head(10)

#Convert timestamp safely to datetime.
df['timestamp'] = pd.to_datetime(
    df['timestamp'],
    errors='coerce',
    utc=True
)

#Remove rows with invalid timestamps
df = df.dropna(subset=['timestamp'])

#Set timestamp as index.
if df.index.name != 'timestamp':
    df.set_index('timestamp', inplace=True)
df.head()

df.index.dtype

#Check missing values.
df.isnull().sum()

#Handle missing HEART RATE values.
df['heart_rate'] = df['heart_rate'].interpolate()

#Handle missing STEPS values.
df['steps'] = df['steps'].ffill()

#Handle missing SLEEP values.
df['sleep'] = df['sleep'].fillna(df['sleep'].mode()[0])

df.isnull().sum()

df.describe()

df.isnull()

#Save Clean Dataset.

df.reset_index(inplace=True)
df.to_csv("/content/clean_Fitpulse_Data.csv", index=False)

print("Preprocessing completed successfully.")

data=pd.read_csv("/content/clean_Fitpulse_Data.csv")
print (df)